# -*- mode: python -*-

Import('env')

env = env.Clone()

libutil_sources = [
    'BufferedLocalFileReader.cpp',
    'BufferedFileReader.cpp',
    'DirIterator.cpp',
    'EncodeConverter.cpp',
    'NormalizeTable.cpp',
    'CHN_T2S_SET.cpp',
    'TimeStamp.cpp',
    'NetFunction.cpp',
    'PersistentMap.cpp',
    'RangeUtil.cpp',
    'XMLFormatUtil.cpp',
    'HaCompressUtil.cpp',
    'IPListParser.cpp',
    'ZlibCompressorWrapper.cpp',
    'memcache/MemCache.cpp',
    'memcache/CacheMap.cpp',
    'memcache/crc.c',
    'ChainedFixedSizePool.cpp',
    'EnvParser.cpp',
    'cityhash/city.cc',
]

env.aLibrary(target = 'ha3_util',
             source = libutil_sources)

env.aProgram(target = 'json_validator',
             source = ['JsonValidator.cpp'],
             LIBS = ['crypto','ssl','snappy', 'arpc', 'kvtracer','kmonitor_client','kmonitor_adapter','fslib-framework',
                     'zookeeper_mt', 'autil', 'protobuf', 'anet', 'alog',
                     'mxml', 'pthread', 'z', 'dl', 'expat','tensorflow_cc','swift_client_minimal','access_log','http_arpc','multi_call','cava_llvm','cava','worker_framework','suez','hiredis','hippo','build_service','future_lite','beeper-framework','indexlib','matchdoc','resource_reader', 'suez_turing', 'amonitor_client'])

env.aDirs('test')
#env.aDirs('perftest')
